# Generated by Django 2.2.9 on 2020-02-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
