# Generated by Django 2.2.9 on 2020-02-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200225_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='daily_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='number_in_stock',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
    ]
